version: '3'
services:
  postgre:
#    image: postgres:12
    build:
      context: ./build/db
    container_name: postgre
    restart: always
    ports:
      - "5432:5432"
#    volumes:
#      - ./build/db/migrations:/docker-entrypoint-initdb.d/



  postgreAndGolang:
    image: golang:latest
    depends_on:
      - postgre
    volumes:
      - .:/go/src/github.com/misterfaradey/PostgreAndGolang/
    working_dir: /go/src/github.com/misterfaradey/PostgreAndGolang/
    ports:
      - "8080:8080"
    entrypoint:
      - go
      - run
      - cmd/api/main.go