# получить предустановленный кошелек
POST http://0.0.0.0:8080/api/wallet/get
Content-Type: application/json

{
  "id":1
}

###
# получить проведденную транзакцию
POST http://0.0.0.0:8080/api/transaction/get
Content-Type: application/json

{
"id":"111"
}
